### ISSUE TITLE
navBar issues

### ISSUE THREAD

**Issue by Hani-AS** [mohammadalnajar/social-media-app#107]
- [x] darkmode slider is a tiny bit visible when the darkmode is active
- [ ] sun inside the slider is not completely centered
- [x] the width of the user avatar inside the navbar gets very tiny when u lower the screen size
- [x] search icon of the search field is hidden when u click on the search field. (gives weird transition)
- [x] the size of the search field decreases when u click it. (because the icon gets removed)
- [x] clicking on the search field needs some transition
- [x] small version (rounded) of the search field is not completely round. 
- [x] FB logo doesn't match the search field logo when lowering the screen size

**Comment by mohammadalnajar** [comment]
2-  Can u provide a photo showing how the sun is not centered? 
3- avatar gets completely hidden on small screens man? photo please to see the problem
